/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package restoran;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.MessageFormat;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class formpemesanan extends javax.swing.JFrame {

   
    public formpemesanan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        disk = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jmlde = new javax.swing.JTextField();
        hrgra = new javax.swing.JTextField();
        hrgdg = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        sub = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        nama = new javax.swing.JTextField();
        jmlra = new javax.swing.JTextField();
        total = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        totalhar = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        btnAdd = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        Reset = new javax.swing.JButton();
        btnprint = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbData = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 0, 102));
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Felix Titling", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("form pemesanan");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(10, 0, 890, 60);

        jLabel2.setFont(new java.awt.Font("Tekton Pro", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Rawoon ULALA yahuuuuud di mulut pas di PERUUT kantong tidak suruuuut");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(10, 50, 610, 20);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 1000, 80);

        jPanel3.setBackground(new java.awt.Color(255, 0, 102));
        jPanel3.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("DISC %");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(10, 380, 70, 30);

        jLabel6.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("DEGAN");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(10, 140, 70, 30);

        jLabel7.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("NAMA");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(10, 20, 60, 30);

        disk.setEditable(false);
        disk.setFont(new java.awt.Font("Perpetua", 1, 18)); // NOI18N
        disk.setForeground(new java.awt.Color(255, 0, 102));
        disk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diskActionPerformed(evt);
            }
        });
        jPanel3.add(disk);
        disk.setBounds(90, 370, 270, 50);

        jLabel8.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("RAWON");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(10, 80, 70, 30);

        jmlde.setFont(new java.awt.Font("Perpetua", 1, 18)); // NOI18N
        jmlde.setForeground(new java.awt.Color(255, 0, 102));
        jmlde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmldeActionPerformed(evt);
            }
        });
        jPanel3.add(jmlde);
        jmlde.setBounds(90, 130, 270, 50);

        hrgra.setEditable(false);
        hrgra.setFont(new java.awt.Font("Perpetua", 1, 18)); // NOI18N
        hrgra.setForeground(new java.awt.Color(255, 0, 102));
        hrgra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hrgraActionPerformed(evt);
            }
        });
        jPanel3.add(hrgra);
        hrgra.setBounds(90, 190, 270, 50);

        hrgdg.setEditable(false);
        hrgdg.setFont(new java.awt.Font("Perpetua", 1, 18)); // NOI18N
        hrgdg.setForeground(new java.awt.Color(255, 0, 102));
        hrgdg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hrgdgActionPerformed(evt);
            }
        });
        jPanel3.add(hrgdg);
        hrgdg.setBounds(90, 250, 270, 50);

        jLabel5.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("RAWON");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(10, 210, 80, 30);

        jLabel9.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("DEGAN");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(10, 270, 70, 30);

        sub.setEditable(false);
        sub.setFont(new java.awt.Font("Perpetua", 1, 18)); // NOI18N
        sub.setForeground(new java.awt.Color(255, 0, 102));
        sub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subActionPerformed(evt);
            }
        });
        jPanel3.add(sub);
        sub.setBounds(90, 430, 270, 50);

        jLabel10.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("TOTAL");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(10, 450, 60, 30);

        nama.setFont(new java.awt.Font("Perpetua", 1, 18)); // NOI18N
        nama.setForeground(new java.awt.Color(255, 0, 102));
        nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaActionPerformed(evt);
            }
        });
        jPanel3.add(nama);
        nama.setBounds(90, 10, 270, 50);

        jmlra.setFont(new java.awt.Font("Perpetua", 1, 18)); // NOI18N
        jmlra.setForeground(new java.awt.Color(255, 0, 102));
        jmlra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmlraActionPerformed(evt);
            }
        });
        jPanel3.add(jmlra);
        jmlra.setBounds(90, 70, 270, 50);

        total.setBackground(new java.awt.Color(255, 255, 255));
        total.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        total.setForeground(new java.awt.Color(255, 0, 102));
        total.setText("TOTAL");
        total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalActionPerformed(evt);
            }
        });
        jPanel3.add(total);
        total.setBounds(150, 490, 130, 40);

        jLabel11.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("HARGA");
        jPanel3.add(jLabel11);
        jLabel11.setBounds(10, 330, 70, 30);

        totalhar.setEditable(false);
        totalhar.setFont(new java.awt.Font("Perpetua", 1, 18)); // NOI18N
        totalhar.setForeground(new java.awt.Color(255, 0, 102));
        totalhar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalharActionPerformed(evt);
            }
        });
        jPanel3.add(totalhar);
        totalhar.setBounds(90, 310, 270, 50);

        jLabel12.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("HARGA ");
        jPanel3.add(jLabel12);
        jLabel12.setBounds(10, 190, 80, 30);

        jLabel13.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("HARGA");
        jPanel3.add(jLabel13);
        jLabel13.setBounds(10, 250, 70, 30);

        jLabel14.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("TOTAL");
        jPanel3.add(jLabel14);
        jLabel14.setBounds(10, 310, 60, 30);

        jLabel15.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("SUB ");
        jPanel3.add(jLabel15);
        jLabel15.setBounds(10, 430, 50, 30);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 150, 370, 640);

        jPanel4.setBackground(new java.awt.Color(255, 0, 102));
        jPanel4.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ISIAN DATA PEMESAN");
        jPanel4.add(jLabel3);
        jLabel3.setBounds(50, 10, 270, 40);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(0, 90, 370, 50);

        jPanel5.setBackground(new java.awt.Color(255, 0, 102));
        jPanel5.setLayout(null);

        btnAdd.setBackground(new java.awt.Color(255, 255, 255));
        btnAdd.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(255, 0, 102));
        btnAdd.setText("SAVE");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jPanel5.add(btnAdd);
        btnAdd.setBounds(10, 10, 90, 30);

        btnDelete.setBackground(new java.awt.Color(255, 255, 255));
        btnDelete.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(255, 0, 102));
        btnDelete.setText("DELETE");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel5.add(btnDelete);
        btnDelete.setBounds(110, 10, 100, 30);

        Reset.setBackground(new java.awt.Color(255, 255, 255));
        Reset.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Reset.setForeground(new java.awt.Color(255, 0, 102));
        Reset.setText("CLEAR");
        Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetActionPerformed(evt);
            }
        });
        jPanel5.add(Reset);
        Reset.setBounds(220, 10, 100, 30);

        btnprint.setBackground(new java.awt.Color(255, 255, 255));
        btnprint.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnprint.setForeground(new java.awt.Color(255, 0, 102));
        btnprint.setText("PRINT");
        btnprint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprintActionPerformed(evt);
            }
        });
        jPanel5.add(btnprint);
        btnprint.setBounds(440, 10, 80, 30);

        btnRefresh.setBackground(new java.awt.Color(255, 255, 255));
        btnRefresh.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnRefresh.setForeground(new java.awt.Color(255, 0, 102));
        btnRefresh.setText("REFRESH");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });
        jPanel5.add(btnRefresh);
        btnRefresh.setBounds(330, 10, 100, 30);

        getContentPane().add(jPanel5);
        jPanel5.setBounds(380, 90, 620, 50);

        jPanel6.setBackground(new java.awt.Color(255, 0, 102));
        jPanel6.setLayout(null);

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setForeground(new java.awt.Color(255, 0, 102));

        tbData.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tbData.setForeground(new java.awt.Color(255, 0, 102));
        tbData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "NAMA", "RAWON", "DEGAN", "HARGA RAWON", "HARGA DEGAN", "DISCOUNT", "TOTAL HARGA", "SUB TOTAL"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbDataMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbData);

        jPanel6.add(jScrollPane2);
        jScrollPane2.setBounds(10, 10, 600, 480);

        getContentPane().add(jPanel6);
        jPanel6.setBounds(380, 150, 620, 640);

        setBounds(0, 0, 1010, 731);
    }// </editor-fold>//GEN-END:initComponents

    private void diskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diskActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_diskActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        if ("".equals(nama.getText()) || "".equals(jmlra.getText()) || "".equals(jmlde.getText()) || "".equals(hrgra.getText()) || "".equals(hrgdg.getText()) || "".equals(disk.getText()) || "".equals(totalhar.getText()) || "".equals(sub.getText()))
        {
            JOptionPane.showMessageDialog(this, "Lengkapi Datamu Dulu Yaa", "Kamu ERROR", JOptionPane.WARNING_MESSAGE);
        } else {
                String SQL = "INSERT INTO tb_transaksi (nama,rawon,degan,hargarawon,hargadegan,discount,totalharga,subtotal) " + "VALUES('"+nama.getText()+"','"+jmlra.getText()+"','"+jmlde.getText()+"','"+hrgra.getText()+"','"+hrgdg.getText()+"','"+disk.getText()+"','"+totalhar.getText()+"','"+sub.getText()+"')";
                int status = KoneksiDB.execute(SQL);
                if (status == 1){
                    JOptionPane.showMessageDialog(this, "Data Kamu Berhasil Ditambahkan", "SUKSES", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(this, "Data Kamu GAGAL Ditambahkan", "GAGAL", JOptionPane.WARNING_MESSAGE);
                }
        }
        
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int baris = tbData.getSelectedRow();
        if (baris != -1) {
            String NAMA = tbData.getValueAt(baris, 0).toString();
            String SQL = "DELETE FROM tb_transaksi WHERE nama='"+NAMA+"'";
            int status = KoneksiDB.execute(SQL);
            if (status == 1){
                JOptionPane.showMessageDialog(this, "Data Kamu Berhasil Dihapus", "SUKSES", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Data Kamu GAGAL Dihapus", "GAGAL", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Kamu Pilih Baris Data Terlebih Dahulu", "ERROR", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetActionPerformed
        // TODO add your handling code here:
        nama.setText("");
        jmlra.setText("");
        jmlde.setText("");
        hrgra.setText("");
        hrgdg.setText("");
        totalhar.setText("");
        disk.setText("");
        sub.setText("");

    }//GEN-LAST:event_ResetActionPerformed

    private void btnprintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprintActionPerformed
        // TODO add your handling code here:
        MessageFormat header = new MessageFormat("RAWON ULALA");
        MessageFormat footer = new MessageFormat("Page (0, number, integer)");
        try{
            tbData.print(JTable.PrintMode.FIT_WIDTH, header, footer, true, null, true, null);    
        } catch (java.awt.print.PrinterException e){
            System.err.format("Cannot print %s%s", e.getMessage());
        }
    }//GEN-LAST:event_btnprintActionPerformed

    private void tbDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbDataMouseClicked
        // TODO add your handling code here:
        int baris = tbData.getSelectedRow();
        if (baris != -1){
            nama.setText(tbData.getValueAt(baris, 0).toString());
            jmlra.setText(tbData.getValueAt(baris, 1).toString());
            jmlde.setText(tbData.getValueAt(baris, 2).toString());
            hrgra.setText(tbData.getValueAt(baris, 3).toString());
            hrgdg.setText(tbData.getValueAt(baris, 4).toString());
            disk.setText(tbData.getValueAt(baris, 5).toString());
            totalhar.setText(tbData.getValueAt(baris, 6).toString());
            sub.setText(tbData.getValueAt(baris, 7).toString());
        }
    }//GEN-LAST:event_tbDataMouseClicked

    private void jmldeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmldeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmldeActionPerformed

    private void hrgraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hrgraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hrgraActionPerformed

    private void hrgdgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hrgdgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hrgdgActionPerformed

    private void subActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subActionPerformed

    private void namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaActionPerformed

    private void jmlraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmlraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmlraActionPerformed

    private void totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalActionPerformed
        // TODO add your handling code here:
       int r = Integer.parseInt(jmlra.getText());
       int d = Integer.parseInt(jmlde.getText());
       int tr = r * 20000;
       int td = d * 5000;
       hrgra.setText(String.valueOf(tr));
       hrgdg.setText(String.valueOf(td));
       int hrawon = Integer.parseInt(hrgra.getText());
       int hdegan = Integer.parseInt(hrgdg.getText());
       int htot = hrawon + hdegan;
       totalhar.setText(String.valueOf(htot));
       if (htot > 200000){
           int diskon = htot * 20 / 100;
           disk.setText(String.valueOf(diskon));
       } else {
           disk.setText(String.valueOf(htot));
       }
       int diss = Integer.parseInt(disk.getText());
       int subtot = htot - diss;
       sub.setText(String.valueOf(subtot));
       
    }//GEN-LAST:event_totalActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        selectData();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void totalharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalharActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalharActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formpemesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formpemesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formpemesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formpemesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formpemesanan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Reset;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnprint;
    private javax.swing.JTextField disk;
    private javax.swing.JTextField hrgdg;
    private javax.swing.JTextField hrgra;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jmlde;
    private javax.swing.JTextField jmlra;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField sub;
    private javax.swing.JTable tbData;
    private javax.swing.JButton total;
    private javax.swing.JTextField totalhar;
    // End of variables declaration//GEN-END:variables

    private void selectData() {
        String kolom[] = {"NAMA","RAWON","DEGAN","HARGA RAWON","HARGA DEGAN","DISCOUNT","TOTAL HARGA","SUB TOTAL"};
        DefaultTableModel dtm = new DefaultTableModel(null, kolom);
        String SQL = "SELECT * FROM tb_transaksi";
        ResultSet rs = KoneksiDB.executeQuery(SQL);
        try{
            while(rs.next()) {
                String Nama = rs.getString(1);
                String Rawon = rs.getString(2);
                String Degan = rs.getString(3);
                String HargaRawon = rs.getString(4);
                String HargaDegan = rs.getString(5);
                String Diskon = rs.getString(6);
                String Totalharga = rs.getString(7);
                String SubTotal = rs.getString(8);
                String data[] = {Nama,Rawon,Degan,HargaRawon,HargaDegan,Diskon,Totalharga,SubTotal};
                dtm.addRow(data);
                            
            }
        } catch (SQLException ex){
            //Logger.getLogger(frmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
        tbData.setModel(dtm);
    }
}
