/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package restoran;

/**
 *
 * @author ASUS
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        SetTanggal();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tanggal = new javax.swing.JTextField();
        kasir1 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        next = new javax.swing.JButton();
        rawon = new javax.swing.JButton();
        degan = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 0, 102));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("News706 BT", 0, 70)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("RAWON ULALA");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(120, 0, 570, 70);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 930, 80);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 102));
        jLabel2.setText("NAMA KASIR");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(10, 10, 120, 22);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 102));
        jLabel3.setText("TANGGAL");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(520, 10, 90, 22);

        tanggal.setEditable(false);
        tanggal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tanggal.setForeground(new java.awt.Color(255, 0, 102));
        jPanel2.add(tanggal);
        tanggal.setBounds(620, 0, 180, 40);

        kasir1.setEditable(false);
        kasir1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        kasir1.setForeground(new java.awt.Color(255, 0, 102));
        kasir1.setText("riri");
        kasir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kasir1ActionPerformed(evt);
            }
        });
        jPanel2.add(kasir1);
        kasir1.setBounds(140, 0, 180, 40);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 80, 930, 40);

        jPanel3.setBackground(new java.awt.Color(255, 0, 102));
        jPanel3.setLayout(null);

        jLabel6.setIcon(new javax.swing.ImageIcon("E:\\TS MATA PELAJARAN\\XI RPL 6\\PBO\\SEMESTER 2\\UTS\\RAA.jpeg")); // NOI18N
        jLabel6.setText("jLabel6");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(40, 20, 400, 320);

        next.setBackground(new java.awt.Color(255, 255, 255));
        next.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        next.setForeground(new java.awt.Color(255, 0, 102));
        next.setText("----->>");
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });
        jPanel3.add(next);
        next.setBounds(680, 470, 120, 31);

        rawon.setBackground(new java.awt.Color(255, 255, 255));
        rawon.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        rawon.setForeground(new java.awt.Color(255, 0, 102));
        rawon.setText("RAWON");
        jPanel3.add(rawon);
        rawon.setBounds(130, 340, 230, 60);

        degan.setBackground(new java.awt.Color(255, 255, 255));
        degan.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        degan.setForeground(new java.awt.Color(255, 0, 102));
        degan.setText("ES DEGAN");
        degan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deganActionPerformed(evt);
            }
        });
        jPanel3.add(degan);
        degan.setBounds(500, 340, 250, 60);

        jLabel14.setIcon(new javax.swing.ImageIcon("E:\\TS MATA PELAJARAN\\XI RPL 6\\PBO\\SEMESTER 2\\UTS\\egg.jpg")); // NOI18N
        jLabel14.setText("jLabel14");
        jPanel3.add(jLabel14);
        jLabel14.setBounds(470, 20, 300, 320);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 120, 870, 510);

        setBounds(0, 0, 830, 666);
    }// </editor-fold>//GEN-END:initComponents

    private void deganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deganActionPerformed

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
        // TODO add your handling code here:
        new formpemesanan().show();
    }//GEN-LAST:event_nextActionPerformed

    private void kasir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kasir1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kasir1ActionPerformed

    private void SetTanggal(){
    java.util.Date now = new java.util.Date();
    java.text.SimpleDateFormat kal = new java.text.SimpleDateFormat("yyy/MM/dd");
    tanggal.setText(kal.format(now));
}
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton degan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField kasir1;
    private javax.swing.JButton next;
    private javax.swing.JButton rawon;
    private javax.swing.JTextField tanggal;
    // End of variables declaration//GEN-END:variables
}


